# ESG Scores Schema
# Environmental, Social, Governance composite and pillar scores

dataset:
  domain: esg
  asset_class: equity
  subdomain: esg_scores
  region: null  # Parameterized
  frequency: yearly  # Annual ESG publication

contract:
  schema_version: schema_v1

  columns:
    - name: ticker
      type: string
      description: Stock ticker symbol (mapped from GVKEY)
      required: true
      filterable: true
      filter_type: in

    - name: gvkey
      type: int
      description: Global Company Key (stable identifier)
      required: true
      filterable: true
      filter_type: in

    - name: esg_year
      type: int
      description: ESG score publication year (e.g., 2023 = scores published in 2023)
      required: true
      filterable: true
      filter_type: range

    - name: year
      type: int
      description: Calendar year when ESG data becomes available for trading (year = esg_year + 1)
      required: true
      filterable: true
      filter_type: range

    - name: esg_score
      type: float
      description: Composite ESG score (0-100)
      required: true
      filterable: true
      filter_type: range

    - name: environmental_pillar_score
      type: float
      description: Environmental component score
      required: true
      filterable: true
      filter_type: range

    - name: social_pillar_score
      type: float
      description: Social component score
      required: true
      filterable: true
      filter_type: range

    - name: governance_pillar_score
      type: float
      description: Governance component score
      required: true
      filterable: true
      filter_type: range

  partition_keys:
    - exchange
    - esg_year

  filters:
    esg_year_range:
      columns: [esg_year]
      type: range
      description: Filter by ESG publication year range
      example: [2020, 2024]

    ticker_list:
      columns: [ticker]
      type: in
      description: Filter to specific tickers
      example: ["AAPL", "MSFT", "GOOGL"]

    score_threshold:
      columns: [esg_score]
      type: range
      description: Filter by ESG score range
      example: [70, 100]

  path_template: data/curated/esg/esg_scores/{schema_version}/exchange={exchange}/esg_year={esg_year}

metadata:
  source: raw/data_matlab_ESG_withSIC.xlsx
  description: |
    ESG (Environmental, Social, Governance) scores from academic research data.
    Includes composite scores and three pillar components.

    ESG scores are published annually. Each company has one record per ESG publication year.

  dependencies:
    - gvkey_mapping

  notes: |
    ESG scores are published annually (YearESG field in raw data).
    Raw data contains monthly observations (YearMonth), but ESG scores are
    constant within each publication year (variance = 0.0).

    This builder extracts one record per company per ESG year to eliminate
    redundant monthly duplicates.

    Coverage: 2006-2024 for US equities
    Companies: ~2,000 unique tickers
    Total observations: ~16,500 annual records (deduplicated from ~197,000 monthly)
