# GVKEY Mapping Schema
# Global Company Key to ticker symbol mapping (metadata)

dataset:
  domain: metadata
  asset_class: null
  subdomain: gvkey_mapping
  region: null
  frequency: null

contract:
  schema_version: schema_v1

  columns:
    - name: gvkey
      type: int
      description: Global Company Key (stable identifier from Compustat)
      required: true
      filterable: true
      filter_type: in

    - name: ticker
      type: string
      description: Normalized ticker symbol (e.g., BRK-B)
      required: true
      filterable: true
      filter_type: in

    - name: ticker_raw
      type: string
      description: Original ticker from source (e.g., BRK.B)
      required: true
      filterable: false

  partition_keys:
    - exchange

  filters:
    ticker_list:
      columns: [ticker]
      type: in
      description: Filter to specific tickers
      example: ["AAPL", "MSFT", "GOOGL"]

    gvkey_list:
      columns: [gvkey]
      type: in
      description: Filter to specific GVKEYs
      example: [1690, 12141, 14593]

  path_template: data/curated/metadata/gvkey_mapping/{schema_version}/exchange={exchange}

parameters:
  exchange:
    type: enum
    values: [US, HK, GLOBAL]
    required: true
    description: Exchange for mapping

metadata:
  source: raw/data_mapping.xlsx
  description: |
    Mapping table from Global Company Keys (GVKEY) to ticker symbols.
    GVKEY is a stable identifier that persists through ticker changes,
    mergers, and corporate actions.

  dependencies: []

  notes: |
    Used by:
      - ESG score builder (maps GVKEY to tickers)
      - Fundamentals data (future)
      - Corporate actions tracking

    GVKEY benefits:
      - Stable across ticker changes (e.g., GOOGL → GOOG → GOOGL)
      - Unique identifier for corporate entities
      - Standard in academic research databases

    Ticker normalization:
      - Converts periods to hyphens (BRK.B → BRK-B)
      - Handles share classes (A, B, etc.)
