# Tiingo OHLCV Price Data Schema
# Daily/Weekly/Monthly equity price data with adjustments

dataset:
  domain: market-data
  asset_class: equity
  subdomain: ohlcv
  frequency: null  # Parameterized

contract:
  schema_version: schema_v1

  columns:
    - name: date
      type: date
      description: Trading date
      required: true
      filterable: true
      filter_type: range

    - name: exchange
      type: string
      description: Exchange identifier (e.g., US, NASDAQ, NYSE)
      required: true
      filterable: true
      filter_type: in

    - name: symbol
      type: string
      description: Ticker symbol
      required: true
      filterable: true
      filter_type: in

    - name: currency
      type: string
      description: Currency code (e.g., USD, HKD)
      required: true
      filterable: true
      filter_type: in

    - name: frequency
      type: string
      description: Data frequency (daily, weekly, monthly)
      required: true
      filterable: false

    - name: open
      type: float
      description: Opening price
      required: true
      filterable: true
      filter_type: range

    - name: high
      type: float
      description: High price
      required: true
      filterable: true
      filter_type: range

    - name: low
      type: float
      description: Low price
      required: true
      filterable: true
      filter_type: range

    - name: close
      type: float
      description: Closing price
      required: true
      filterable: true
      filter_type: range

    - name: volume
      type: int
      description: Trading volume
      required: true
      filterable: true
      filter_type: range

    - name: adj_open
      type: float
      description: Adjusted opening price (splits & dividends)
      required: true
      filterable: true
      filter_type: range

    - name: adj_high
      type: float
      description: Adjusted high price
      required: true
      filterable: true
      filter_type: range

    - name: adj_low
      type: float
      description: Adjusted low price
      required: true
      filterable: true
      filter_type: range

    - name: adj_close
      type: float
      description: Adjusted closing price
      required: true
      filterable: true
      filter_type: range

    - name: adj_volume
      type: int
      description: Adjusted volume
      required: true
      filterable: true
      filter_type: range

    - name: div_cash
      type: float
      description: Cash dividend amount
      required: true
      filterable: true
      filter_type: range

    - name: split_factor
      type: float
      description: Stock split factor
      required: true
      filterable: true
      filter_type: range

    - name: source
      type: string
      description: Data source (tiingo)
      required: true
      filterable: false

  partition_keys:
    - exchange
    - frequency
    - symbol
    - year

  filters:
    date_range:
      columns: [date]
      type: range
      description: Filter by trading date range
      example: ["2020-01-01", "2024-12-31"]

    symbol_list:
      columns: [symbol]
      type: in
      description: Filter to specific symbols
      example: ["AAPL", "MSFT", "GOOGL"]

    price_range:
      columns: [adj_close]
      type: range
      description: Filter by adjusted closing price range
      example: [100, 500]

    volume_threshold:
      columns: [volume]
      type: range
      description: Filter by trading volume threshold
      example: [1000000, null]

  path_template: data/curated/market-data/ohlcv/{schema_version}/exchange={exchange}/frequency={frequency}/symbol={symbol}/year={year}

parameters:
  exchange:
    type: enum
    values: [US, NYSE, NASDAQ, HKEX, LSE]
    required: true
    description: Stock exchange

  frequency:
    type: enum
    values: [daily, weekly, monthly]
    required: true
    description: Data frequency (daily, weekly, monthly)

metadata:
  source: Tiingo API (https://api.tiingo.com/)
  description: |
    Equity OHLCV (Open, High, Low, Close, Volume) price data with corporate
    action adjustments. Includes both raw and adjusted prices, dividends,
    and split factors.

  dependencies: []

  notes: |
    - Adjusted prices account for splits and dividends
    - Year-based partitioning for efficient time-series queries
    - Supports multiple frequencies: daily, weekly (Friday close), monthly (end-of-month)
    - Historical data available from company IPO date
